### ISSUE TITLE
1.13.1 error

### ISSUE THREAD

**Issue by MCMANY** [megamichiel/AnimatedMenu#17]
### command

[15:42:39 INFO]: MCMANY issued server command: /FIeldSelectMenu
[15:42:39 WARN]: java.lang.NoSuchFieldException: b
[15:42:39 WARN]: at java.lang.Class.getDeclaredField(Unknown Source)
[15:42:39 WARN]: at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:458)
[15:42:39 WARN]: at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:471)
[15:42:39 WARN]: at me.libraryaddict.disguise.utilities.ReflectionManager.convertSoundEffectToString(ReflectionManager.java:759)
[15:42:39 WARN]: at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:71)
[15:42:39 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[15:42:39 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[15:42:39 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[15:42:39 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[15:42:39 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1394)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1367)
[15:42:39 WARN]: at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.playSound(CraftPlayer.java:426)
[15:42:39 WARN]: at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.playSound(CraftPlayer.java:413)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.command.SoundCommand$SoundInfo.play(SoundInfo.java:91)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.Menu$Settings.lambda$addListener$0(Settings.java:331)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.Menu.lambda$open$5(Menu.java:200)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.AbstractMenu.setup(AbstractMenu.java:180)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.Menu.openInventory(Menu.java:138)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.Menu.open(Menu.java:208)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.Menu.open(Menu.java:152)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.menu.Menu.onCommand(Menu.java:244)
[15:42:39 WARN]: at me.megamichiel.animatedmenu.plus.iliili.onCommand(iliili.java:121)
[15:42:39 WARN]: at me.megamichiel.animationlib.command.CommandInfo.execute(CommandInfo.java:93)
[15:42:39 WARN]: at me.megamichiel.animationlib.bukkit.BukkitCommandAPI$2.execute(BukkitCommandAPI.java:164)
[15:42:39 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:42:39 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:696)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1644)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[15:42:39 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:42:39 WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[15:42:39 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[15:42:39 WARN]: at java.lang.Thread.run(Unknown Source)

### trigger

[15:59:00 WARN]: java.lang.NoSuchFieldException: b
[15:59:00 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:458)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:471)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.convertSoundEffectToString(ReflectionManager.java:759)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:71)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1394)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1367)
[15:59:00 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.playSound(CraftPlayer.java:426)
[15:59:00 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.playSound(CraftPlayer.java:413)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.command.SoundCommand$SoundInfo.play(SoundInfo.java:91)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu$Settings.lambda$addListener$0(Settings.java:331)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.lambda$open$5(Menu.java:200)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.AbstractMenu.setup(AbstractMenu.java:180)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.openInventory(Menu.java:138)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.open(Menu.java:208)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.open(Menu.java:152)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.plus.ililii.e(ililii.java:133)
[15:59:00 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:59:00 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:59:00 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:59:00 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:59:00 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[15:59:00 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:59:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:59:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1826)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[15:59:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:59:00 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[15:59:00 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:59:00 WARN]: java.lang.NoSuchFieldException: b
[15:59:00 WARN]:        at java.lang.Class.getDeclaredField(Unknown Source)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:458)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.getNmsField(ReflectionManager.java:471)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.ReflectionManager.convertSoundEffectToString(ReflectionManager.java:759)
[15:59:00 WARN]:        at me.libraryaddict.disguise.utilities.packetlisteners.PacketListenerSounds.onPacketSending(PacketListenerSounds.java:71)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[15:59:00 WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1394)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1367)
[15:59:00 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.playSound(CraftPlayer.java:426)
[15:59:00 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.playSound(CraftPlayer.java:413)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.command.SoundCommand$SoundInfo.play(SoundInfo.java:91)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu$Settings.lambda$addListener$0(Settings.java:331)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.lambda$open$5(Menu.java:200)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.AbstractMenu.setup(AbstractMenu.java:180)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.openInventory(Menu.java:138)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.open(Menu.java:208)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.menu.Menu.open(Menu.java:152)
[15:59:00 WARN]:        at me.megamichiel.animatedmenu.plus.ililii.e(ililii.java:133)
[15:59:00 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:59:00 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:59:00 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:59:00 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[15:59:00 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[15:59:00 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:59:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:59:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1826)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[15:59:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:59:00 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[15:59:00 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[15:59:00 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by megamichiel** [comment]
This is caused by Lib's Disguises, something related to intercepting sent sounds. This can be found on the plugin's page at https://www.spigotmc.org/resources/libs-disguises.32453/:
"Lib's Disguises is intended to be run only on: 1.11.2 and 1.12

You can try the 1.13.1 builds here! While 1.13.1 builds are being tested, testing is limited to paid customers only!"
