### ISSUE TITLE
1.14.1 No such method found getOrDefault

### ISSUE THREAD

**Issue by merijnlioen** [megamichiel/AnimatedMenu#20]
When I try to load the plugin in 1.14.1 I get the following error

> 18.05 13:53:37 [Server] Server thread/WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.IRegistry.getOrDefault(net.minecraft.server.v1_14_R1.MinecraftKey)
18.05 13:53:37 [Server] Server thread/WARN at java.lang.Class.getDeclaredMethod(Class.java:2130)
18.05 13:53:37 [Server] Server thread/WARN at me.megamichiel.animatedmenu.util.item.MaterialParser.<clinit>(MaterialParser.java:48)
18.05 13:53:37 [Server] Server thread/WARN at me.megamichiel.animatedmenu.AnimatedMenuPlugin.parseItemStack(AnimatedMenuPlugin.java:470)
18.05 13:53:37 [Server] Server thread/WARN at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadSettings(ConfigMenuProvider.java:227)
18.05 13:53:37 [Server] Server thread/WARN at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadMenu(ConfigMenuProvider.java:167)
18.05 13:53:37 [Server] Server thread/WARN at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadMenus(ConfigMenuProvider.java:125)
18.05 13:53:37 [Server] Server thread/WARN at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadConfig(ConfigMenuProvider.java:84)
18.05 13:53:37 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
18.05 13:53:37 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
18.05 13:53:37 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008)
18.05 13:53:37 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
18.05 13:53:37 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
18.05 13:53:37 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
18.05 13:53:37 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:745)
1

**Comment by megamichiel** [comment]
I've identified the issue and resolved it for the next update.
