### ISSUE TITLE
Task #11 for AnimatedMenu v3.2.7 generated an exception

### ISSUE THREAD

**Issue by Kruemmelspalter** [megamichiel/AnimatedMenu#26]
```
[12:23:06 INFO]: [AnimatedMenu] Loading menus...
[12:23:07 WARN]: [AnimatedMenu] Invalid data value: red
[12:23:07 WARN]: [AnimatedMenu] Invalid data value: green
[12:23:07 WARN]: [AnimatedMenu] Task #11 for AnimatedMenu v3.2.7 generated an exception
java.lang.NullPointerException
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuItem.<init>(ConfigMenuItem.java:228) ~[?:?]
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadItem(ConfigMenuProvider.java:299) ~[?:?]
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.lambda$loadMenu$1(ConfigMenuProvider.java:197) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_265]
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadMenu(ConfigMenuProvider.java:197) ~[?:?]
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadMenu(ConfigMenuProvider.java:167) ~[?:?]
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadMenus(ConfigMenuProvider.java:124) ~[?:?]
	at me.megamichiel.animatedmenu.menu.config.ConfigMenuProvider.loadConfig(ConfigMenuProvider.java:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

I installed Vault, EssentialsX and AnimationLib

**Comment by Kruemmelspalter** [comment]
Ok... I think the example just doesn't work for 1.8 anymore
