### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by GMatrixGames** [megamichiel/AnimatedMenu#5]
[17:49:15 WARN]: Unexpected exception while parsing console command "animatedmen
u reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'anim
atedmenu' in plugin AnimatedMenu v3.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spi
got.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServe
r.java:645) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchServerCommand(Craf
tServer.java:631) [Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.DedicatedServer.aL(DedicatedServer.java:
437) [Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:4
00) [Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapp
ing
 in 'string', line 75, column 5:
        1:
        ^
expected <block end>, but found Anchor
 in 'string', line 77, column 8:
        - '&bThere are &a%pinger_players_pl ...
           ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(Par
serImpl.java:570) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~
[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:224) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~
[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:229) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~
[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.jav
a:199) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153) ~
[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java
:229) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~
[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:12
2) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
 ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseCons
tructor.java:120) ~[Spigot.jar:git-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[Spigot.jar:gi
t-Spigot-4af49dc-c5e9a16]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427) ~[Spigot.jar:git-Spigot
-4af49dc-c5e9a16]
        at me.megamichiel.animationlib.config.type.YamlConfig.lambda$loadFromStr
ing$0(YamlConfig.java:40) ~[?:?]
        at me.megamichiel.animationlib.config.MapConfig.deserialize(MapConfig.ja
va:237) ~[?:?]
        at me.megamichiel.animationlib.config.type.YamlConfig.loadFromString(Yam
lConfig.java:40) ~[?:?]
        at me.megamichiel.animationlib.config.MapConfig.loadFromFile(MapConfig.j
ava:258) ~[?:?]
        at me.megamichiel.animationlib.config.ConfigManager.reloadConfig(ConfigM
anager.java:83) ~[?:?]
        at me.megamichiel.animationlib.config.ConfigManager.getConfig(ConfigMana
ger.java:94) ~[?:?]
        at me.megamichiel.animationlib.config.ConfigManager.quickLoad(ConfigMana
ger.java:15) ~[?:?]
        at me.megamichiel.animatedmenu.menu.config.MenuLoader.loadMenus(MenuLoad
er.java:112) ~[?:?]
        at me.megamichiel.animatedmenu.menu.config.MenuLoader.loadMenus(MenuLoad
er.java:79) ~[?:?]
        at me.megamichiel.animatedmenu.menu.config.MenuLoader.loadConfig(MenuLoa
der.java:68) ~[?:?]
        at me.megamichiel.animatedmenu.AnimatedMenuPlugin.reload(AnimatedMenuPlu
gin.java:330) ~[?:?]
        at me.megamichiel.animatedmenu.AnimatedMenuCommand.lambda$new$10(Animate
dMenuCommand.java:142) ~[?:?]
        at me.megamichiel.animatedmenu.AnimatedMenuCommand.onCommand(AnimatedMen
uCommand.java:166) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spi
got.jar:git-Spigot-4af49dc-c5e9a16]
        ... 8 more
--------------------------------------------------------------------------------------------------

**Comment by GMatrixGames** [comment]
I don't know what to do!

**Comment by GMatrixGames** [comment]
Plz halp ASAP

**Comment by megamichiel** [comment]
Could you show me your menu file, particularly around line 77?
In this version I haven't included much detail about which menu it is, but the line involved is - '&bThere are &a%pinger_players_pl ...

**Comment by GMatrixGames** [comment]
I can, but in 7 hrs bc I have school

**Comment by GMatrixGames** [comment]
Menu-Name:
  1: '&aServer Selector'
Title-Update-Delay: 40

Menu-Type: chest
Rows: 6

Permission: matrixnet.Selector
Permission-Message: '&cYou are not allowed to open this menu!'

Menu-Opener: compass:1:0
Menu-Opener-Name: '&aServer Selector'
Menu-Opener-Lore:
- '&aPick a server to go to'
Menu-Opener-Slot: 5

Open-On-Join: no
Open-Sound: ui.button.click 1 0

Hide-From-Command: true
Command:
  Name: servers
  Usage: '/servers'
  Description: 'Open the server selector'
  Fallback: say

Click-Delay: 20
Delay-Message: '&cYou need to wait another {ticksleft} ticks for that!'

Items:
- Slot: 4
  Frame-Delay: 200
  Refresh-Delay: 100
  Material:
    1: 'TNT:1:0'
  Name:
    1: '&c&lFactions 1&r %pinger_online_play.matrixnetwork.net:25568%'
  Lore:
    1:
    - '&bCome fight for what's right!'
    - '&bThere are &a%pinger_players_play.matrixnetwork.net:25568%&b / &a%pinger_max_play.matrixnetwork.net:25568%&b players online!'
  Enchantments:
  - 'unbreaking:1'
  Hide-Flags: enchants
  Hide-Permission: some.item.permission
  Commands:
  - 'op:server Factions1'

- Slot: 6
  Frame-Delay: 200
  Refresh-Delay: 100
  Material:
    1: 'TNT:1:0'
  Name:
    1: '&c&lFactions 2&r %pinger_online_play.matrixnetwork.net:25569%'
  Lore:
    1:
    - '&bCome fight for what's right!'
    - '&bThere are &a%pinger_players_play.matrixnetwork.net:25569%&b / &a%pinger_max_play.matrixnetwork.net:25569%&b players online!'
  Enchantments:
  - 'unbreaking:1'
  Hide-Flags: enchants
  Hide-Permission: some.item.permission
  Commands:
  - 'op:server Factions2'
  
- Slot: 5
  Frame-Delay: 200
  Refresh-Delay: 100
  Material:
    1: 'BEDROCK:1:0'
  Name:
    1: '&c&lOP Factions&r %pinger_online_play.matrixnetwork.net:25570%'
  Lore:
    1:
    - '&bCome fight for what's right!'
    - '&4Overpaoered version of the traditional &cFactions!' 
    - '&bThere are &a%pinger_players_play.matrixnetwork.net:25570%&b / &a%pinger_max_play.matrixnetwork.net:25570%&b players online!'
  Enchantments:
  - 'unbreaking:1'
  Hide-Flags: enchants
  Hide-Permission: some.item.permission
  Commands:
  - 'op:server OPFactions'

- Slot: 1
  Frame-Delay: 200
  Refresh-Delay: 100
  Material:
    1: 'IRON_BARS:1:0'
  Name:
    1: '&7&lJail 1&r %pinger_online_play.matrixnetwork.net:25568%'
  Lore:
    1:
    - '&7&lHACKER ONLY SERVER!'
    - '&bThere are &a%pinger_players_play.matrixnetwork.net:25568%&b / &a%pinger_max_play.matrixnetwork.net:25568%&b players online!'
  Enchantments:
  - 'unbreaking:1'
  Hide-Flags: enchants
  Hide-Permission: some.item.permission
  Commands:
  - 'op:server Jail'

**Comment by GMatrixGames** [comment]
^^^^ That is my config

**Comment by megamichiel** [comment]
Try this: https://pastebin.com/qnaNZ62M
I replaced the 's from "Come fight for what's right" with ''s. The single quotes are used around the entire text, so using them breaks the config. By using double 's a regular ' is displayed.

**Comment by GMatrixGames** [comment]
Thank you!
